version: "3"

services: 
    flask_server:
        # container_name: flask_app
        restart: always
        build: ./flask_app
        expose: 
            - "8000"
        networks: 
            - "mlapp_net"
        command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
    
    nginx_server:
        # container_name: nginx
        restart: always
        build: ./nginx
        environment:
            - SERVER_NAME="0.0.0.0"
        ports:
            - "80:80"
            # - "443:443"
        networks: 
            - "mlapp_net"
        depends_on:
            - flask_server

networks:
    mlapp_net:
        driver: bridge